### ISSUE TITLE
Explore the Codebase and Read up on Documentation

### ISSUE THREAD

**Issue by M-Hassan-Raza** [recursive-rewind/October-22-2022#3]
Explore the code and discover the frameworks and tools used by the React-Storefront Devs

**Comment by umer-farooq1784** [comment]
React Storefront is basically a java framework that provides you with a fastest build e-commerce website or you can say a boiler code for your website which contains basic necessary components for an e-commerce website. 

React Storefront is based on **React And Next.js mainly**, yet it contains some other techs also like
TypeScript
GraphQL with Apollo Client
Tailwind CSS
Turborepo
Saleor Checkout


Prefetching content for connected pages is simple with React Storefront, allowing you to stay one step ahead of your users and offer seamless page transitions.

**Comment by M-Hassan-Raza** [comment]
Good work Umer, please continue exploring this repository and documentation further. We'll need your insights when doing API testing.
