### ISSUE TITLE
Decide and Explore the Testing Framework

### ISSUE THREAD

**Issue by M-Hassan-Raza** [recursive-rewind/October-22-2022#4]
Explore NightWatch and Cucumber to set up the stage for further stages of the testing

**Comment by Taimoor2500** [comment]
Things to know 
1) javaScript (https://www.w3schools.com/js/)



Using Nightwatch for testing 
https://blog.risingstack.com/end-to-end-testing-with-nightwatch-js-node-js-at-scale/  use this as a reference to configure Nightwatch

Reason:
Provides a clean syntax that lets you write tests rapidly.  It allows the use of CSS as well as XPath selectors to locate elements. It works seamlessly with cloud-based testing platforms like LambdaTest. CI (Continuous Integration) support – Integrates your testing with systems like Teamcity, Hudson, and Jenkins.

make sure to create a folder and use the command  --save-dev to save to files in the package

download chrome driver


create a nightwatch config file

use this to initialize the file

module.exports = {
    'src_folders': ['tests'],
   

    'webdriver': {
        'start_process': true,
        'server_path': require('chromedriver').path,
        'port': 9515
    },

    'test_settings': {
        'default': {
            
            'desiredCapabilities':
             {
                'browserName': 'chrome',
                
            }
        }
    }
};


create a test config file in folder tests
initialize it with  


module.exports = {
    'My first test case'(browser) {
        browser
            .url('http://localhost:3000')
            .waitForElementVisible('body')
           // .pause(1000)
           //.waitForElementVisible('.MuiIconButton-label')

           .click('MuiIconButton-label')
            

           // .waitForElementVisible('.MuiButton-label')
       
            
           
        // .assert.containsText('.MuiButton-label', 'Add to Cart');
    }
};

**Comment by M-Hassan-Raza** [comment]
Excellent work Taimoor. This will greatly help the team in getting started with the API testing. Let's circle back to this topic again in the upcoming meeting.
