### ISSUE TITLE
Decide, Explore and Do Basic Implementation of the Automation Framework

### ISSUE THREAD

**Issue by M-Hassan-Raza** [recursive-rewind/October-22-2022#5]
Explore JEST and how we can use this automated framework to optimize our testing workflow so that we don't have to do manual testing every time the code changes.

**Comment by Taimoor2500** [comment]
visit https://jestjs.io/

Generate code coverage by adding the flag [--coverage](https://jestjs.io/docs/cli#--coverageboolean). No additional setup needed. Jest can collect code coverage information from entire projects, including untested files.


It is recommended to define the configuration in a dedicated JavaScript, TypeScript or JSON file. The file will be discovered automatically, if it is named jest.config.js|ts|mjs|cjs|json. You can use [--config](https://jestjs.io/docs/cli#--configpath) flag to pass an explicit path to the file.


/** @returns {Promise<import('jest').Config>} */
module.exports = async () => {
  return {
    verbose: true,
  };
};

visit https://jestjs.io/docs/configuration for better clarification or contact me if facing implementation issues on monday anytime between 1 to 2 30 pm or 4 to 5 30pm

**Comment by M-Hassan-Raza** [comment]
Good Work. We'll explore this topic further in upcoming meeting, Insha'Allah.
